blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('users/', include('django.contrib.auth.urls')),
    path('update/', include('updates.urls', namespace='updates')),
    path('contact/', include('contact_us.urls', namespace='contact')),
    path('prayers/', include('prayers.urls', namespace='prayers')),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prayers/urls.py
from django.urls import path
from . import views

app_name = 'prayers'

urlpatterns = [
    path('', views.PrayerListView.as_view(), name='prayer_list'),
    path('prayer/<int:pk>', views.PrayerDetailView.as_view(), name='prayer_detail'),
    path('prayer/', views.CreatePrayerView.as_view(), name='create_prayer'),
    path('prayer/<int:pk>/edit/', views.PrayerUpdateView.as_view(), name='prayer_edit'),
    path('prayer/<int:pk>/remove/', views.PrayerDeleteView.as_view(), name='prayer_remove'),
]

prayers/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import redirect

# Create your models here.

class Prayer(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=500)
    date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('prayers:prayer_detail',kwargs={'pk':self.pk})


    def __str__(self):
        return self.title

prayers/forms.py
from django import forms
from .models import Prayer

class PrayerForm(forms.ModelForm):

    class Meta:
        model = Prayer
        fields = ['title','content']

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

prayers/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Prayer
from .forms import PrayerForm
from django.utils import timezone
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
decorators = [user_passes_test(lambda u:u.is_superuser)]

class PrayerListView(LoginRequiredMixin, ListView):
    model = Prayer

    def get_queryset(self):
        return Prayer.objects.filter(date__lte=timezone.now()).order_by('-date')

class PrayerDetailView(LoginRequiredMixin, DetailView):
    model = Prayer

@method_decorator(decorators, name='dispatch')
class CreatePrayerView(CreateView):
    redirect_field_name = 'index.html'
    form_class = PrayerForm
    model = Prayer


@method_decorator(decorators, name='dispatch')
class PrayerUpdateView(UpdateView):
    redirect_field_name = 'prayers/prayer_list.html'
    form_class = PrayerForm
    model = Prayer


@method_decorator(decorators, name='dispatch')
class PrayerDeleteView(DeleteView):
    model = Prayer
    success_url = reverse_lazy('prayers:prayer_list')

prayers/templates/prayers/prayer_confirm_delete.html
{% extends 'base.html'%}

{% block content%}
 <h2>Are you sure?</h2>
 <form method="post">
   {% csrf_token %}
   <input type="submit" class='btn btn-danger' value="Delete">
 </form>
{% endblock%}

prayers/templates/prayers/prayer_detail.html
{% extends 'base.html'%}

{% block content%}

  <h1>{{prayer.title}}</h1>
  <p>{{prayer.content}}</p>

{% if user.is_superuser %}
  <a class="btn btn-primary" href="{% url 'prayers:prayer_edit' pk=prayer.pk%}"><span class="fa fa-pencil"></span></a>
  <a class="btn btn-primary" href="{% url 'prayers:prayer_remove' pk=prayer.pk%}"><span class="fa fa-remove"></span></a>
{% endif %}

{% endblock%}

prayers/templates/prayers/prayer_edit.html
{% extends 'base.html'%}

prayers/templates/prayers/prayer_form.html
{% extends 'base.html'%}

{% block content %}

  {% if user.is_superuser%}
    <h1>Add New Prayer Request</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add</button>

    </form>
  {% endif%}
{% endblock %}

prayers/templates/prayers/prayer_list.html
{% extends 'base.html'%}

{% block content %}

  {% for prayer in prayer_list %}

    <div class="prayer">
       <a href="{% url 'prayers:prayer_detail' pk=prayer.pk%}"><h3>{{prayer.title|safe}}</h3></a>
      <p>{{prayer.date|date:'m-d-y'}}</p>
      <p>{{prayer.content|truncatewords:30}}</p>
    </div>


  {% endfor%}

    {% if user.is_superuser %}
      <a class="btn btn-primary" href="{% url 'prayers:create_prayer'%}">Add</a>
    {% endif%}

{% endblock %}