blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('users/', include('django.contrib.auth.urls')),
    path('update/', include('updates.urls', namespace='updates')),
    path('contact/', include('contact_us.urls', namespace='contact')),
    path('prayers/', include('prayers.urls', namespace='prayers')),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

updates/urls.py
from . import views
from django.urls import path

app_name = 'updates'


urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),


]

updates/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)
    slug = models.SlugField(null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approve_comments=True)

    def get_absolute_url(self):
        return reverse('updates:post_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('updates.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comments = models.BooleanField(default=False)

    def approve(self):
        self.approved_comments = True
        self.save()

    def get_abolute_url(self):
        return reverse('updates:post_list', kwargs={'pk':self.pk})

    def __str__(self):
        return self.text

updates/forms.py
from django import forms
from .models import Post, Comment
from django_summernote.widgets import SummernoteWidget

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['author','title','text']

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':SummernoteWidget(),
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author','text')

#Might need to add aditional lines here from blog project?

#attrs={'class':'editable medium-editor-textarea postcontent'}

updates/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail, EmailMultiAlternatives

from .models import Post, Comment
from .forms import PostForm, CommentForm
from users.models import CustomUser

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


decorators = [user_passes_test(lambda u: u.is_superuser)]

# Create your views here.
class PostListView(LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

@method_decorator(decorators, name='dispatch')
class CreatePostView(CreateView):
    redirect_field_name = 'updates/post_detail.html'

    form_class = PostForm

    model = Post

@method_decorator(decorators, name='dispatch')
class PostUpdateView(UpdateView):
    redirect_field_name = 'updates/post_detail.html'

    form_class = PostForm

    model = Post

@method_decorator(decorators, name='dispatch')
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('updates:post_list')

@method_decorator(decorators, name='dispatch')
class DraftListView(ListView):
    redirect_field_name = 'updates/post_draft_list.html'

    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')






@user_passes_test(lambda u: u.is_superuser)
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    email_list = get_emails()
    for email in email_list:
        html_message = render_to_string('updates/new_post_email.html', {'id':pk, 'email':email})
        plain_msg = strip_tags(html_message)
        send_mail('New Update from the Joneses To Read!', plain_msg, 'noreply@jonezfam.com', [email,], html_message=html_message, fail_silently=False)
    post.publish()
    return redirect("updates:post_list")


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('updates:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'updates/comment_form.html', {'form': form})


@user_passes_test(lambda u: u.is_superuser)
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('updates:post_detail', pk=comment.post.pk)


@user_passes_test(lambda u: u.is_superuser)
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('updates:post_detail', pk=post_pk)


def get_emails():
    users = CustomUser.objects.all()
    email_list = []
    for user in users:
        if user.email_update == True:
            email_list.append(user.email)
    return email_list

updates/templates/updates/comment_form.html
{% extends 'base.html'%}

{% block content %}

  <h1>New Comment</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-default" type="submit">Add Comment</button>
  </form>

{% endblock %}

updates/templates/updates/new_post_email.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Post</title>
    <link rel="stylesheet" href="email_style.css">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
</head>

<body>
    <div class="container">
        <h1 class="title">New Post!</h1>
        <p>The Jones have finally found the time to write down all the recent events that they've experienced.
            You should go read it before you forget; After all, you never know what those crazies have been up to!</p>
        <h3>Click <a href="https://www.jonezfam.com/update/post/{{id}}">here</a> to read it
        </h3>
    </div>
    <div>
        <p>If you don't want emails for this kind of thing, click <a
                href="https://www.jonezfam.com/users/email/{{email}}/">here</a> to change your email preferences.</p>
    </div>

</body>

</html>

updates/templates/updates/post_confirm_delete.html
{% extends 'base.html'%}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}}?</p>
    <input class="btn btn-danger" type="submit" value="Confirm">
  </form>
{% endblock %}

updates/templates/updates/post_detail.html
{% extends 'base.html'%}

{% block content %}


    <h1 class="posttitle">{{post.title}}</h1>

    {%if post.published_date %}
      <div class="postdate">
        <br>
        <h4>Author: {{post.author}}</h4>
        {{post.published_date}}
      </div>
    {% else %}
       <a class="btn btn-outline-dark" href="{% url 'updates:post_publish' pk=post.pk%}">Publish</a>
    {% endif%}
    <div class="container">
      <div class="postcontent">
        <p>{{ post.text|safe|linebreaksbr}}</p>
      </div>

    </div>

    {% if user.is_superuser %}
      <a class="btn btn-primary" href="{% url 'updates:post_edit' pk=post.pk %}"><span class="fa fa-pencil"></span></a>
      <a class="btn btn-primary" href="{% url 'updates:post_remove' pk=post.pk %}"><span class="fa fa-remove"></span></a>
    {% endif %}

<hr>
<a class="btn btn-primary btn-comment" href="{% url 'updates:add_comment_to_post' pk=post.pk %}">Comment</a>

<div class="container">
  {% for comment in post.comments.all%}
  <br>
      {% if user.is_superuser or comment.approved_comments %}
          {% if not comment.approved_comments %}
              <a class="btn btn-primary" href="{% url 'updates:comment_remove' pk=comment.pk %}"><span class="fa fa-remove"></span></a>
              <a class="btn btn-primary" href="{% url 'updates:comment_approve' pk=comment.pk %}"><span class="fa fa-check"></span></a>
          {% endif %}
            Comment by: {{comment.author}}, on {{comment.created_date|date:'m/d/y'}}
          {{comment.text|safe|linebreaks }}



      {% endif %}
  {% empty %}
    <p>Be the first to comment!</p>
  {% endfor%}

</div>
{% endblock %}

updates/templates/updates/post_draft_list.html
{% extends 'base.html'%}

{% block content %}

    {% for post in posts %}
        <div class="post">
            <p>created: {{post.created_date|date 'd-m-y'}}</p>
            <h1><a href="{% url 'updates:post_detail' pk=post.pk%}">{{post.title}}</a></h1>
            <p>{{post.text|truncatechars:200}}</p>
        </div>
      {% endfor%}
{% endblock %}

updates/templates/updates/post_form.html
{% extends 'base.html'%}

{% block content %}
    <h1>New Post</h1>
    <form method="post">
      {% csrf_token %}
      {{form.media}}
      {{form.as_p}}
      <button type="submit" class="btn btn-default">Save</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

updates/templates/updates/post_list.html
{% extends 'base.html'%}

{% block content %}

<div class="container postlist">

    {% for post in post_list %}
        <div class="post">
          <h1><a href="{% url 'updates:post_detail' pk=post.pk%}">{{ post.title }}</a></h1>
          <div class="date">
              <p>Published on: {{ post.published_date|date:'m/d/yy'}}</p>
              <p>{{post.text|safe|truncatewords:30}}</p>
          </div>
        </div>
    {% endfor %}
</div>

{% endblock %}