blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('users/', include('django.contrib.auth.urls')),
    path('update/', include('updates.urls', namespace='updates')),
    path('contact/', include('contact_us.urls', namespace='contact')),
    path('prayers/', include('prayers.urls', namespace='prayers')),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact_us/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'contact_us'

urlpatterns = [
    path('contactform/', views.emailView, name='email'),
]

prayers/urls.py
from django.urls import path
from . import views

app_name = 'prayers'

urlpatterns = [
    path('', views.PrayerListView.as_view(), name='prayer_list'),
    path('prayer/<int:pk>', views.PrayerDetailView.as_view(), name='prayer_detail'),
    path('prayer/', views.CreatePrayerView.as_view(), name='create_prayer'),
    path('prayer/<int:pk>/edit/', views.PrayerUpdateView.as_view(), name='prayer_edit'),
    path('prayer/<int:pk>/remove/', views.PrayerDeleteView.as_view(), name='prayer_remove'),
]

updates/urls.py
from . import views
from django.urls import path

app_name = 'updates'


urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),


]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.custom_signup, name='signup'),
    path('email/<slug>/', views.EmailOpt.as_view()),

]

templates/about.html
{% extends 'base.html'%}

{% block content %}

{% if user.is_authenticated %}
<p></p><h3>Our Family</h3>
<p><br></p><p><img class="aboutpicture" src="/media/django-summernote/2020-04-14/493a9f9c-a4ad-42f2-a947-cd8a50054b64.JPG" style="width: 25%; float: left;">
</p><h3>Timothy A. Jones</h3><p>I graduated from Master’s Baptist College with a Bachelors in Pastoral Studies.
  I enjoy programming, and using it to enable us to reach people with the gospel. I also enjoy fishing and hiking,
  especially mountaineering, and learning new skills.</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>
  <h3><img class="aboutpicture" src="/media/django-summernote/2020-04-14/a8153f66-05bc-4b00-b464-98b00c8077af.JPG" style="width: 25%; float: left;">Sarah L. Jones</h3>
  <div>I enjoy learning ASL &amp; I love to spend time with my family. I have an amazing
    husband and twin girls that were not a surprise, but rather an answer to prayer. I am
    constantly reminded of God’s sufficient grace as I look at the family God has given to
    me, &amp; as I live each day able to do many things I was once unable to, due to my health.
    Although it can be challenging, I greatly enjoy the blessings of being a wife &amp; a mom to twins.
    My greatest desire is to serve the Lord to the best of my ability whether that be here in the States
    or on the mission field in a foreign</div>
    <div>country.</div>
    <div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>
    <h3><img class="aboutpicture" src="/media/django-summernote/2020-04-14/10a934db-f9a3-4cfa-8750-fa5d784bb8c9.jpg" style="width: 25%; float: left;" >Joanna G. Jones</h3><div>
      <div>I am the firstborn &amp; my favorite thing to do is bounce whether laying on the ground, sitting
        on the couch, or standing in a jumper. I was born with bilateral strabismus &amp; had a
        corrective eye surgery at just 6 months old. Thankfully, my eyes are now perfectly aligned, &amp;
        I can see just as well as my sister.
      </div></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>
      <div><img class="aboutpicture" src="/media/django-summernote/2020-04-14/47a9c900-b4ef-4603-9592-3e91c738be81.jpg" style="width: 25%; float: left;" >
        <h3>Susanna G. Jones</h3></div><div><div>I was born just minutes after my sister, and yet
          I have been the bigger sister since long before we were born. I love to eat, &amp; for some
          strange reason, I have a bit of a foot fetish; it doesn’t matter whose foot it is, I want
          to play with it. Although I love my mom, I am a major daddy’s girl, and I get very excited
          whenever my daddy comes into sight.</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><h4>Anniversary: August 18th</h4><div><br></div><h4>Birthdays:</h4><h4>Timothy - May 9th</h4><h4>Sarah - February 8th<h4>Joanna - May 11th, 2019</h4><h4>Susanna - May 11th, 2019</h4></h4><div><br></div></div><p>
          </p>

{% else %}
<div class="jumbotron">
        <style>
          .imagebackground{background-image:none;}
        </style>
    <div class="loginsignup">
      <h2>Please Log In or Sign Up</h2>
      <a class="btn btn-primary btn-lg" href="{% url 'users:login'%}" role='button'>Log In</a>
      <a class="btn btn-primary btn-lg" href="{% url 'users:signup'%}" role='button'>Sign Up</a>
    </div>
</div>




{% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Jones Family</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

      {# MEDIUM STYLE EDITOR#}
      <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

      {# Custom CSS#}
      <link rel="stylesheet" href="{% static 'css/master.css' %}">

      <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">


  </head>
  <body class="imagebackground">

    <nav class="navbar navbar-expand-lg navbar-light custnav" role="navigation">
      <div class="container">
        {% if user.is_authenticated %}
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand" href="{% url 'home'%}">Home</a>
          <a class="nav-item nav-link" href="{% url 'updates:post_list'%}" class="btn btn-simple">Updates</a>
          <a class="nav-item nav-link" href="{% url 'prayers:prayer_list'%}" class="btn btn-simple">Prayer Requests</a>
          <a class="nav-item nav-link" href="{% url 'about'%}" class="btn btn-simple">About Us</a>
        </div>
        <div class="navbar-nav ml-auto">
            {% if user.is_superuser%}
              <a class="nav-item nav-link" href="{%url 'updates:post_new'%}" class="btn btn-simple">Post</a>
              <a class="nav-item nav-link" href="{%url 'updates:post_draft_list'%}" class="btn btn-simple">Drafts</a>
            {% endif %}
          <a class="nav-item nav-link" href="{% url 'contact_us:email'%}" class="btn btn-simple">Contact Us</a>
          <a class="nav-item nav-link" href="{% url 'accounts:logout'%}" class="btn btn-simple">Log Out</a>

          {% endif %}
        </div>
      </div>
    </nav>

        <div class="container contentblock">

          {%block content %}
          {% endblock %}

        </div>


          <div class="indexfooter">
            {% if user.is_superuser %}
              <a href="{% url 'admin:index'%}">Admin</a>
            {% endif %}
          </div>

  </body>
</html>

templates/index.html
{% extends 'base.html'%}

{% block content%}




<div class="container">

    {% if user.is_authenticated %}

          <div class="centerstage">

            <h1>Welcome!</h1>
            <a class="btn btn-primary homebutton" href="{% url 'updates:post_list' %}">Read an Update</a>
            <a class="btn btn-primary homebutton" href="{% url 'prayers:prayer_list' %}">Prayer Requests</a>

          </div>

    {% else %}
      <div class="jumbotron">
              <style>
                .imagebackground{background-image:none;}
              </style>
          <div class="loginsignup">
            <h2>Please Log In or Sign Up</h2>
            <a class="btn btn-primary btn-lg" href="{% url 'users:login'%}" role='button'>Log In</a>
            <a class="btn btn-primary btn-lg" href="{% url 'users:signup'%}" role='button'>Sign Up</a>
          </div>
      </div>
    {% endif %}
  </div>

{% endblock%}

templates/signup.html
{% extends 'base.html'%}

{% load bootstrap4 %}


{% block content %}


    {% if messages %}
      {% for message in messages%}
          <div class="alert alert-dark" role="alert">

            {{message}}
          </div>

      {% endfor %}
    {% endif %}


<style>
  .imagebackground{background-image:none;}
</style>

  <div class="container">
    <h1>Sign up</h1>
    <form class="form" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
      {% endbuttons %}

    </form>
  </div>


{%endblock%}